spring:
  application:
    name: help-desk-backened

  datasource:
    url: jdbc:mysql://localhost:3306/helpdesk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

#Open: https://console.groq.com
#Sign in with Google/GitHub.
#Click API Keys → Create API Key

Copy the key → store it in:
groq:
  api:
    key: ""
    url: "https://api.groq.com/openai/v1/chat/completions"


server:
  port: 8081

logging:
  level:
    com.helpdesk: DEBUG
    org.springframework.web: INFO
